# Generated by Django 5.2.15 on 2026-08-18 16:14

import contentops.models
import core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentAssetVersion',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('object_key', models.CharField(max_length=1024)),
                ('mime_type', models.CharField(max_length=255)),
                ('byte_size', models.PositiveBigIntegerField()),
                ('content_sha256', models.CharField(max_length=64, validators=[contentops.models.validate_sha256])),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('manifest_sha256', models.CharField(blank=True, max_length=64, validators=[contentops.models.validate_sha256])),
                ('creation_command_id', models.UUIDField(unique=True)),
                ('creation_payload_hash', models.CharField(blank=True, max_length=64, validators=[contentops.models.validate_sha256])),
                ('created_by_acting_role', models.CharField(choices=[('OWNER', 'Owner'), ('OPERATIONS_ADMIN', 'Operations admin'), ('OPERATOR', 'Operator')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['content_asset_id', 'version_number'],
            },
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('CHANGES_REQUESTED', 'Changes requested'), ('REJECTED', 'Rejected')], max_length=24)),
                ('rationale', models.TextField()),
                ('criteria_results', models.JSONField(blank=True, default=dict)),
                ('decision_sha256', models.CharField(blank=True, max_length=64, validators=[contentops.models.validate_sha256])),
                ('command_id', models.UUIDField(unique=True)),
                ('payload_hash', models.CharField(blank=True, max_length=64, validators=[contentops.models.validate_sha256])),
                ('expected_task_version', models.PositiveIntegerField()),
                ('reviewer_acting_role', models.CharField(choices=[('OWNER', 'Owner'), ('OPERATIONS_ADMIN', 'Operations admin'), ('OPERATOR', 'Operator')], max_length=24)),
                ('decided_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['decided_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('submission_number', models.PositiveIntegerField()),
                ('asset_manifest', models.JSONField()),
                ('submission_note', models.TextField(blank=True)),
                ('manifest_sha256', models.CharField(blank=True, max_length=64, validators=[contentops.models.validate_sha256])),
                ('command_id', models.UUIDField(unique=True)),
                ('payload_hash', models.CharField(blank=True, max_length=64, validators=[contentops.models.validate_sha256])),
                ('expected_task_version', models.PositiveIntegerField()),
                ('submitted_by_acting_role', models.CharField(choices=[('OWNER', 'Owner'), ('OPERATIONS_ADMIN', 'Operations admin'), ('OPERATOR', 'Operator')], max_length=24)),
                ('sealed_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['task_id', 'submission_number'],
            },
        ),
        migrations.CreateModel(
            name='TaskSubmissionAssetLink',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('PRIMARY', 'Primary deliverable'), ('SUPPORTING', 'Supporting deliverable')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentAsset',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('asset_key', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=240)),
                ('asset_kind', models.CharField(choices=[('VIDEO', 'Video'), ('IMAGE', 'Image'), ('COPY', 'Copy'), ('DOCUMENT', 'Document'), ('OTHER', 'Other')], max_length=16)),
                ('description', models.TextField(blank=True)),
                ('creation_command_id', models.UUIDField(unique=True)),
                ('creation_payload_hash', models.CharField(max_length=64, validators=[contentops.models.validate_sha256])),
                ('created_by_acting_role', models.CharField(choices=[('OWNER', 'Owner'), ('OPERATIONS_ADMIN', 'Operations admin'), ('OPERATOR', 'Operator')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_assets_created', to=settings.AUTH_USER_MODEL)),
                ('created_under_grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_assets_created', to='accounts.permissiongrant')),
                ('recorded_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_assets_recorded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
