# Generated by Django 5.2.15 on 2026-08-18 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('contentops', '0001_initial'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentasset',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_assets', to='workflow.task'),
        ),
        migrations.AddField(
            model_name='contentassetversion',
            name='content_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='contentops.contentasset'),
        ),
        migrations.AddField(
            model_name='contentassetversion',
            name='created_by_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_asset_versions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentassetversion',
            name='created_under_grant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_asset_versions_created', to='accounts.permissiongrant'),
        ),
        migrations.AddField(
            model_name='contentassetversion',
            name='recorded_by_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='content_asset_versions_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewdecision',
            name='recorded_by_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_decisions_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewdecision',
            name='reviewer_grant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_decisions_made', to='accounts.permissiongrant'),
        ),
        migrations.AddField(
            model_name='reviewdecision',
            name='reviewer_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_decisions_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='dod_check_run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sealed_submission', to='workflow.taskcheckrun'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='primary_asset_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_for_submissions', to='contentops.contentassetversion'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='recorded_by_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_submissions_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='submitted_by_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_submissions_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='submitted_under_grant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_submissions_made', to='accounts.permissiongrant'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='supersedes_submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_submission', to='contentops.tasksubmission'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='workflow.task'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='triggering_review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rework_submission', to='contentops.reviewdecision'),
        ),
        migrations.AddField(
            model_name='reviewdecision',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='final_review', to='contentops.tasksubmission'),
        ),
        migrations.AddField(
            model_name='tasksubmissionassetlink',
            name='asset_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_links', to='contentops.contentassetversion'),
        ),
        migrations.AddField(
            model_name='tasksubmissionassetlink',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_links', to='contentops.tasksubmission'),
        ),
        migrations.AddConstraint(
            model_name='contentasset',
            constraint=models.UniqueConstraint(fields=('task', 'asset_key'), name='contentops_unique_asset_key_per_task'),
        ),
        migrations.AddConstraint(
            model_name='contentasset',
            constraint=models.CheckConstraint(condition=models.Q(('asset_key', ''), _negated=True), name='contentops_asset_key_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='contentassetversion',
            constraint=models.UniqueConstraint(fields=('content_asset', 'version_number'), name='contentops_unique_asset_version'),
        ),
        migrations.AddConstraint(
            model_name='contentassetversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gte', 1)), name='contentops_asset_version_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='contentassetversion',
            constraint=models.CheckConstraint(condition=models.Q(('object_key', ''), _negated=True), name='contentops_object_key_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='tasksubmission',
            constraint=models.UniqueConstraint(fields=('task', 'submission_number'), name='contentops_unique_submission_number'),
        ),
        migrations.AddConstraint(
            model_name='tasksubmission',
            constraint=models.CheckConstraint(condition=models.Q(('submission_number__gte', 1)), name='contentops_submission_number_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='tasksubmission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('submission_number', 1), ('supersedes_submission__isnull', True), ('triggering_review__isnull', True)), models.Q(('submission_number__gt', 1), ('supersedes_submission__isnull', False)), _connector='OR'), name='contentops_submission_rework_reference'),
        ),
        migrations.AddConstraint(
            model_name='tasksubmissionassetlink',
            constraint=models.UniqueConstraint(fields=('submission', 'asset_version'), name='contentops_unique_submission_asset'),
        ),
        migrations.AddConstraint(
            model_name='tasksubmissionassetlink',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'PRIMARY')), fields=('submission',), name='contentops_one_primary_link_per_submission'),
        ),
    ]
