# Generated by Django 5.2.15 on 2026-08-19 16:56

from django.db import migrations, models
from django.db.models import F


def legacy_integrity_failures(*, self_review_ids, submission_rows):
    """Return bounded descriptions of historical facts that violate V1 P0 invariants."""

    by_id = {row["id"]: row for row in submission_rows}
    invalid_chain_ids = []
    for row in submission_rows:
        previous_id = row["supersedes_submission_id"]
        if previous_id is None:
            continue
        previous = by_id.get(previous_id)
        if (
            previous is None
            or previous_id == row["id"]
            or previous["task_id"] != row["task_id"]
            or previous["submission_number"] + 1 != row["submission_number"]
        ):
            invalid_chain_ids.append(row["id"])
            if len(invalid_chain_ids) == 20:
                break

    failures = []
    if self_review_ids:
        failures.append(f"self-review ReviewDecision ids={list(self_review_ids)}")
    if invalid_chain_ids:
        failures.append(f"invalid TaskSubmission chain ids={invalid_chain_ids}")
    return failures


def audit_legacy_integrity(apps, schema_editor):
    """Refuse to install guards on top of already-invalid historical facts."""

    alias = schema_editor.connection.alias
    ReviewDecision = apps.get_model("contentops", "ReviewDecision")
    TaskSubmission = apps.get_model("contentops", "TaskSubmission")

    self_review_ids = list(
        ReviewDecision.objects.using(alias)
        .filter(reviewer_principal_id=F("submission__submitted_by_principal_id"))
        .values_list("id", flat=True)[:20]
    )

    rows = list(
        TaskSubmission.objects.using(alias).values(
            "id", "task_id", "submission_number", "supersedes_submission_id"
        )
    )
    failures = legacy_integrity_failures(self_review_ids=self_review_ids, submission_rows=rows)
    if failures:
        raise RuntimeError(
            "Refusing contentops integrity migration; repair historical data first: " + "; ".join(failures)
        )


def mark_existing_review_payloads_v1(apps, schema_editor):
    ReviewDecision = apps.get_model("contentops", "ReviewDecision")
    ReviewDecision.objects.using(schema_editor.connection.alias).filter(
        payload_schema_version__isnull=True
    ).update(payload_schema_version=1)


def create_integrity_triggers(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "sqlite":
        for suffix, operation in (("insert", "INSERT"), ("update", "UPDATE")):
            schema_editor.execute(
                f"""
                CREATE TRIGGER contentops_submission_chain_{suffix}
                BEFORE {operation} ON contentops_tasksubmission
                WHEN NEW.supersedes_submission_id IS NOT NULL
                     AND NOT EXISTS (
                         SELECT 1
                         FROM contentops_tasksubmission previous
                         WHERE previous.id = NEW.supersedes_submission_id
                           AND previous.id <> NEW.id
                           AND previous.task_id = NEW.task_id
                           AND previous.submission_number + 1 = NEW.submission_number
                     )
                BEGIN
                    SELECT RAISE(ABORT, 'invalid task submission supersession chain');
                END;
                """
            )
            schema_editor.execute(
                f"""
                CREATE TRIGGER contentops_review_no_self_{suffix}
                BEFORE {operation} ON contentops_reviewdecision
                WHEN EXISTS (
                    SELECT 1
                    FROM contentops_tasksubmission submission
                    WHERE submission.id = NEW.submission_id
                      AND submission.submitted_by_principal_id = NEW.reviewer_principal_id
                )
                BEGIN
                    SELECT RAISE(ABORT, 'submitter cannot review own submission');
                END;
                """
            )
        return

    if vendor == "postgresql":
        schema_editor.execute(
            """
            CREATE FUNCTION contentops_enforce_submission_chain() RETURNS trigger AS $$
            BEGIN
                IF NEW.supersedes_submission_id IS NOT NULL AND NOT EXISTS (
                    SELECT 1
                    FROM contentops_tasksubmission previous
                    WHERE previous.id = NEW.supersedes_submission_id
                      AND previous.id <> NEW.id
                      AND previous.task_id = NEW.task_id
                      AND previous.submission_number + 1 = NEW.submission_number
                ) THEN
                    RAISE EXCEPTION 'invalid task submission supersession chain'
                        USING ERRCODE = '23514';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """
        )
        schema_editor.execute(
            """
            CREATE TRIGGER contentops_submission_chain_guard
            BEFORE INSERT OR UPDATE ON contentops_tasksubmission
            FOR EACH ROW EXECUTE FUNCTION contentops_enforce_submission_chain();
            """
        )
        schema_editor.execute(
            """
            CREATE FUNCTION contentops_enforce_no_self_review() RETURNS trigger AS $$
            BEGIN
                IF EXISTS (
                    SELECT 1
                    FROM contentops_tasksubmission submission
                    WHERE submission.id = NEW.submission_id
                      AND submission.submitted_by_principal_id = NEW.reviewer_principal_id
                ) THEN
                    RAISE EXCEPTION 'submitter cannot review own submission'
                        USING ERRCODE = '23514';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """
        )
        schema_editor.execute(
            """
            CREATE TRIGGER contentops_review_no_self_guard
            BEFORE INSERT OR UPDATE ON contentops_reviewdecision
            FOR EACH ROW EXECUTE FUNCTION contentops_enforce_no_self_review();
            """
        )


def drop_integrity_triggers(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "sqlite":
        for name in (
            "contentops_submission_chain_insert",
            "contentops_submission_chain_update",
            "contentops_review_no_self_insert",
            "contentops_review_no_self_update",
        ):
            schema_editor.execute(f"DROP TRIGGER IF EXISTS {name};")
        return
    if vendor == "postgresql":
        schema_editor.execute(
            "DROP TRIGGER IF EXISTS contentops_submission_chain_guard ON contentops_tasksubmission;"
        )
        schema_editor.execute("DROP FUNCTION IF EXISTS contentops_enforce_submission_chain();")
        schema_editor.execute(
            "DROP TRIGGER IF EXISTS contentops_review_no_self_guard ON contentops_reviewdecision;"
        )
        schema_editor.execute("DROP FUNCTION IF EXISTS contentops_enforce_no_self_review();")


class Migration(migrations.Migration):

    dependencies = [
        ('contentops', '0002_initial'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(audit_legacy_integrity, migrations.RunPython.noop),
        migrations.AddField(
            model_name='reviewdecision',
            name='payload_schema_version',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.RunPython(mark_existing_review_payloads_v1, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='reviewdecision',
            name='payload_schema_version',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'Legacy review command'), (2, 'Reviewer-bound review command')],
                default=2,
            ),
        ),
        migrations.AddConstraint(
            model_name='tasksubmission',
            constraint=models.CheckConstraint(condition=models.Q(('id', models.F('supersedes_submission_id')), _negated=True), name='contentops_submission_cannot_supersede_self'),
        ),
        migrations.RunPython(create_integrity_triggers, drop_integrity_triggers),
    ]
