# Generated by Django 5.2.15 on 2026-08-22

import core.ids
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intelligence", "0001_initial"),
        ("products", "0002_claimmatrixversion_and_more"),
        ("accounts", "0005_secretreference_permissiongrant_supersedes_grant_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.CreateModel(
            name="EvidenceInvalidationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=core.ids.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("command_id", models.UUIDField(unique=True)),
                ("payload_hash", models.CharField(max_length=64)),
                ("reason", models.TextField()),
                (
                    "acting_role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("OPERATIONS_ADMIN", "Operations admin"),
                            ("OPERATOR", "Operator"),
                        ],
                        max_length=24,
                    ),
                ),
                ("invalidated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evidence_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invalidation_event",
                        to="intelligence.externalevidenceitem",
                    ),
                ),
                (
                    "invalidated_by_principal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_invalidations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "permission_grant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_invalidation_events",
                        to="accounts.permissiongrant",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evidence_invalidation_events",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
