# Generated by Django 5.2.15 on 2026-08-21 09:05

import core.ids
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('releasegate', '0004_alter_publication_requested_by_acting_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GEOProbePanel',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('panel_key', models.CharField(max_length=120)),
                ('version_number', models.PositiveIntegerField()),
                ('market_code', models.CharField(max_length=16)),
                ('language_code', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='geo_probe_panels', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='GEOProbePanelItem',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('item_number', models.PositiveIntegerField()),
                ('question', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='insights.geoprobepanel')),
            ],
        ),
        migrations.CreateModel(
            name='GEOProbeResult',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('availability_state', models.CharField(choices=[('PRESENT', 'Present'), ('MISSING', 'Missing'), ('BLOCKED', 'Blocked'), ('UNAVAILABLE', 'Unavailable'), ('INVALIDATED', 'Invalidated')], max_length=16)),
                ('response_text', models.TextField(blank=True)),
                ('brand_mentioned', models.BooleanField(default=False)),
                ('rank_position', models.PositiveIntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('panel_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='insights.geoprobepanelitem')),
            ],
        ),
        migrations.CreateModel(
            name='GEOProbeCitation',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('citation_number', models.PositiveIntegerField()),
                ('cited_url', models.URLField(max_length=1024)),
                ('cited_title', models.CharField(blank=True, max_length=512)),
                ('cited_domain', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citations', to='insights.geoproberesult')),
            ],
        ),
        migrations.CreateModel(
            name='GEOProbeRun',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('run_key', models.CharField(max_length=160, unique=True)),
                ('provider', models.CharField(max_length=64)),
                ('model_reference', models.CharField(max_length=160)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], max_length=16)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='insights.geoprobepanel')),
            ],
        ),
        migrations.AddField(
            model_name='geoproberesult',
            name='probe_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='insights.geoproberun'),
        ),
        migrations.CreateModel(
            name='LearningVersion',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('learning_key', models.CharField(max_length=160)),
                ('version_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=240)),
                ('conclusion', models.TextField()),
                ('recommended_action', models.TextField()),
                ('confidence', models.DecimalField(decimal_places=4, max_digits=5)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PROPOSED', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_versions', to='products.product')),
                ('supersedes_version', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_version', to='insights.learningversion')),
            ],
        ),
        migrations.CreateModel(
            name='MetricCollectionRun',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('run_key', models.CharField(max_length=160, unique=True)),
                ('data_domain', models.CharField(choices=[('CONTENT_PERFORMANCE', 'Content performance'), ('SEARCH_VISIBILITY', 'Search visibility'), ('COMMERCE_OUTCOME', 'Commerce outcome'), ('PROCESS_TELEMETRY', 'Process telemetry'), ('GEO', 'Generative-engine visibility')], max_length=32)),
                ('source_kind', models.CharField(choices=[('API', 'API'), ('BROWSER', 'Browser'), ('CSV', 'CSV'), ('MANUAL', 'Manual'), ('SYSTEM', 'System')], max_length=16)),
                ('source_reference', models.CharField(blank=True, max_length=512)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], max_length=16)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('metric_key', models.CharField(max_length=120)),
                ('version_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('data_domain', models.CharField(choices=[('CONTENT_PERFORMANCE', 'Content performance'), ('SEARCH_VISIBILITY', 'Search visibility'), ('COMMERCE_OUTCOME', 'Commerce outcome'), ('PROCESS_TELEMETRY', 'Process telemetry'), ('GEO', 'Generative-engine visibility')], max_length=32)),
                ('value_kind', models.CharField(choices=[('COUNT', 'Count'), ('RATIO', 'Ratio'), ('CURRENCY', 'Currency'), ('SCORE', 'Score'), ('DURATION', 'Duration')], max_length=16)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetricCollectionRunMetric',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('data_domain', models.CharField(choices=[('CONTENT_PERFORMANCE', 'Content performance'), ('SEARCH_VISIBILITY', 'Search visibility'), ('COMMERCE_OUTCOME', 'Commerce outcome'), ('PROCESS_TELEMETRY', 'Process telemetry'), ('GEO', 'Generative-engine visibility')], max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('collection_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metric_links', to='insights.metriccollectionrun')),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_run_links', to='insights.metricdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='GEOMetricObservation',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('data_domain', models.CharField(choices=[('CONTENT_PERFORMANCE', 'Content performance'), ('SEARCH_VISIBILITY', 'Search visibility'), ('COMMERCE_OUTCOME', 'Commerce outcome'), ('PROCESS_TELEMETRY', 'Process telemetry'), ('GEO', 'Generative-engine visibility')], max_length=32)),
                ('availability_state', models.CharField(choices=[('PRESENT', 'Present'), ('MISSING', 'Missing'), ('BLOCKED', 'Blocked'), ('UNAVAILABLE', 'Unavailable'), ('INVALIDATED', 'Invalidated')], max_length=16)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=8, max_digits=28, null=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('observed_at', models.DateTimeField()),
                ('source_reference', models.CharField(blank=True, max_length=1024)),
                ('correction_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recorded_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supersedes_observation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_observation', to='insights.geometricobservation')),
                ('probe_result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metric_observations', to='insights.geoproberesult')),
                ('collection_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_observations', to='insights.metriccollectionrun')),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_observations', to='insights.metricdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='CommerceObservation',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('data_domain', models.CharField(choices=[('CONTENT_PERFORMANCE', 'Content performance'), ('SEARCH_VISIBILITY', 'Search visibility'), ('COMMERCE_OUTCOME', 'Commerce outcome'), ('PROCESS_TELEMETRY', 'Process telemetry'), ('GEO', 'Generative-engine visibility')], max_length=32)),
                ('availability_state', models.CharField(choices=[('PRESENT', 'Present'), ('MISSING', 'Missing'), ('BLOCKED', 'Blocked'), ('UNAVAILABLE', 'Unavailable'), ('INVALIDATED', 'Invalidated')], max_length=16)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=8, max_digits=28, null=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('observed_at', models.DateTimeField()),
                ('source_reference', models.CharField(blank=True, max_length=1024)),
                ('correction_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('touchpoint', models.CharField(choices=[('PRODUCT_VIEW', 'Product view'), ('ADD_TO_CART', 'Add to cart'), ('CHECKOUT', 'Checkout'), ('PURCHASE', 'Purchase'), ('REVENUE', 'Revenue')], max_length=24)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commerce_observations', to='products.product')),
                ('recorded_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supersedes_observation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_observation', to='insights.commerceobservation')),
                ('collection_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_observations', to='insights.metriccollectionrun')),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_observations', to='insights.metricdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelPerformanceObservation',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('data_domain', models.CharField(choices=[('CONTENT_PERFORMANCE', 'Content performance'), ('SEARCH_VISIBILITY', 'Search visibility'), ('COMMERCE_OUTCOME', 'Commerce outcome'), ('PROCESS_TELEMETRY', 'Process telemetry'), ('GEO', 'Generative-engine visibility')], max_length=32)),
                ('availability_state', models.CharField(choices=[('PRESENT', 'Present'), ('MISSING', 'Missing'), ('BLOCKED', 'Blocked'), ('UNAVAILABLE', 'Unavailable'), ('INVALIDATED', 'Invalidated')], max_length=16)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=8, max_digits=28, null=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('observed_at', models.DateTimeField()),
                ('source_reference', models.CharField(blank=True, max_length=1024)),
                ('correction_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_observations', to='releasegate.channelaccount')),
                ('recorded_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supersedes_observation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_observation', to='insights.channelperformanceobservation')),
                ('collection_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_observations', to='insights.metriccollectionrun')),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_observations', to='insights.metricdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationPerformanceObservation',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('data_domain', models.CharField(choices=[('CONTENT_PERFORMANCE', 'Content performance'), ('SEARCH_VISIBILITY', 'Search visibility'), ('COMMERCE_OUTCOME', 'Commerce outcome'), ('PROCESS_TELEMETRY', 'Process telemetry'), ('GEO', 'Generative-engine visibility')], max_length=32)),
                ('availability_state', models.CharField(choices=[('PRESENT', 'Present'), ('MISSING', 'Missing'), ('BLOCKED', 'Blocked'), ('UNAVAILABLE', 'Unavailable'), ('INVALIDATED', 'Invalidated')], max_length=16)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=8, max_digits=28, null=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('observed_at', models.DateTimeField()),
                ('source_reference', models.CharField(blank=True, max_length=1024)),
                ('correction_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('collection_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_observations', to='insights.metriccollectionrun')),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_observations', to='insights.metricdefinition')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_observations', to='releasegate.publication')),
                ('recorded_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supersedes_observation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_observation', to='insights.publicationperformanceobservation')),
            ],
        ),
        migrations.CreateModel(
            name='SearchProperty',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('property_key', models.CharField(max_length=255)),
                ('provider', models.CharField(choices=[('GOOGLE_SEARCH_CONSOLE', 'Google Search Console'), ('GOOGLE_SEARCH', 'Google Search')], max_length=32)),
                ('canonical_url', models.URLField(max_length=1024)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='search_properties', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='SearchIndexObservation',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('data_domain', models.CharField(choices=[('CONTENT_PERFORMANCE', 'Content performance'), ('SEARCH_VISIBILITY', 'Search visibility'), ('COMMERCE_OUTCOME', 'Commerce outcome'), ('PROCESS_TELEMETRY', 'Process telemetry'), ('GEO', 'Generative-engine visibility')], max_length=32)),
                ('availability_state', models.CharField(choices=[('PRESENT', 'Present'), ('MISSING', 'Missing'), ('BLOCKED', 'Blocked'), ('UNAVAILABLE', 'Unavailable'), ('INVALIDATED', 'Invalidated')], max_length=16)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=8, max_digits=28, null=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('observed_at', models.DateTimeField()),
                ('source_reference', models.CharField(blank=True, max_length=1024)),
                ('correction_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('inspected_url', models.URLField(max_length=1024)),
                ('collection_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_observations', to='insights.metriccollectionrun')),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_observations', to='insights.metricdefinition')),
                ('recorded_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supersedes_observation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_observation', to='insights.searchindexobservation')),
                ('search_property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='index_observations', to='insights.searchproperty')),
            ],
        ),
        migrations.CreateModel(
            name='SearchVisibilityObservation',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('data_domain', models.CharField(choices=[('CONTENT_PERFORMANCE', 'Content performance'), ('SEARCH_VISIBILITY', 'Search visibility'), ('COMMERCE_OUTCOME', 'Commerce outcome'), ('PROCESS_TELEMETRY', 'Process telemetry'), ('GEO', 'Generative-engine visibility')], max_length=32)),
                ('availability_state', models.CharField(choices=[('PRESENT', 'Present'), ('MISSING', 'Missing'), ('BLOCKED', 'Blocked'), ('UNAVAILABLE', 'Unavailable'), ('INVALIDATED', 'Invalidated')], max_length=16)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=8, max_digits=28, null=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('dimensions', models.JSONField(blank=True, default=dict)),
                ('observed_at', models.DateTimeField()),
                ('source_reference', models.CharField(blank=True, max_length=1024)),
                ('correction_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('query_text', models.CharField(max_length=512)),
                ('collection_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_observations', to='insights.metriccollectionrun')),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_observations', to='insights.metricdefinition')),
                ('recorded_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('search_property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visibility_observations', to='insights.searchproperty')),
                ('supersedes_observation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_observation', to='insights.searchvisibilityobservation')),
            ],
        ),
        migrations.CreateModel(
            name='LearningEvidenceLink',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('source_kind', models.CharField(choices=[('PUBLICATION_PERFORMANCE', 'Publication performance'), ('CHANNEL_PERFORMANCE', 'Channel performance'), ('SEARCH_VISIBILITY', 'Search visibility'), ('SEARCH_INDEX', 'Search index'), ('COMMERCE', 'Commerce'), ('GEO', 'GEO')], max_length=32)),
                ('evidence_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('channel_performance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learning_links', to='insights.channelperformanceobservation')),
                ('commerce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learning_links', to='insights.commerceobservation')),
                ('geo_metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learning_links', to='insights.geometricobservation')),
                ('learning_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_links', to='insights.learningversion')),
                ('publication_performance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learning_links', to='insights.publicationperformanceobservation')),
                ('search_index', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learning_links', to='insights.searchindexobservation')),
                ('search_visibility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='learning_links', to='insights.searchvisibilityobservation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='geoprobepanel',
            constraint=models.UniqueConstraint(fields=('panel_key', 'version_number'), name='insights_unique_geo_panel_version'),
        ),
        migrations.AddConstraint(
            model_name='geoprobepanel',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gte', 1)), name='insights_geo_panel_version_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='geoprobepanelitem',
            constraint=models.UniqueConstraint(fields=('panel', 'item_number'), name='insights_unique_geo_panel_item'),
        ),
        migrations.AddConstraint(
            model_name='geoprobepanelitem',
            constraint=models.CheckConstraint(condition=models.Q(('item_number__gte', 1)), name='insights_geo_item_number_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='geoprobecitation',
            constraint=models.UniqueConstraint(fields=('result', 'citation_number'), name='insights_unique_geo_citation_number'),
        ),
        migrations.AddConstraint(
            model_name='geoprobecitation',
            constraint=models.CheckConstraint(condition=models.Q(('citation_number__gte', 1)), name='insights_geo_citation_number_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='geoproberun',
            constraint=models.CheckConstraint(condition=models.Q(('completed_at__gte', models.F('started_at'))), name='insights_geo_run_time_valid'),
        ),
        migrations.AddConstraint(
            model_name='geoproberesult',
            constraint=models.UniqueConstraint(fields=('probe_run', 'panel_item'), name='insights_unique_geo_run_item'),
        ),
        migrations.AddConstraint(
            model_name='learningversion',
            constraint=models.UniqueConstraint(fields=('learning_key', 'version_number'), name='insights_unique_learning_version'),
        ),
        migrations.AddConstraint(
            model_name='learningversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gte', 1)), name='insights_learning_version_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='learningversion',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', Decimal('0')), ('confidence__lte', Decimal('1'))), name='insights_learning_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='metriccollectionrun',
            constraint=models.CheckConstraint(condition=models.Q(('window_end__gt', models.F('window_start'))), name='insights_run_window_valid'),
        ),
        migrations.AddConstraint(
            model_name='metriccollectionrun',
            constraint=models.CheckConstraint(condition=models.Q(('completed_at__gte', models.F('started_at'))), name='insights_run_time_valid'),
        ),
        migrations.AddConstraint(
            model_name='metricdefinition',
            constraint=models.UniqueConstraint(fields=('metric_key', 'version_number'), name='insights_unique_metric_version'),
        ),
        migrations.AddConstraint(
            model_name='metricdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gte', 1)), name='insights_metric_version_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='metricdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('metric_key', ''), _negated=True), name='insights_metric_key_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='metriccollectionrunmetric',
            constraint=models.UniqueConstraint(fields=('collection_run', 'metric_definition'), name='insights_unique_run_metric'),
        ),
        migrations.AddConstraint(
            model_name='geometricobservation',
            constraint=models.CheckConstraint(condition=models.Q(('data_domain', 'GEO')), name='insights_geo_metric_domain'),
        ),
        migrations.AddConstraint(
            model_name='geometricobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('availability_state', 'PRESENT'), ('numeric_value__isnull', False)), models.Q(models.Q(('availability_state', 'PRESENT'), _negated=True), ('numeric_value__isnull', True)), _connector='OR'), name='insights_geo_metric_availability'),
        ),
        migrations.AddConstraint(
            model_name='commerceobservation',
            constraint=models.CheckConstraint(condition=models.Q(('data_domain', 'COMMERCE_OUTCOME')), name='insights_commerce_obs_domain'),
        ),
        migrations.AddConstraint(
            model_name='commerceobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('availability_state', 'PRESENT'), ('numeric_value__isnull', False)), models.Q(models.Q(('availability_state', 'PRESENT'), _negated=True), ('numeric_value__isnull', True)), _connector='OR'), name='insights_commerce_obs_availability'),
        ),
        migrations.AddConstraint(
            model_name='channelperformanceobservation',
            constraint=models.CheckConstraint(condition=models.Q(('data_domain', 'CONTENT_PERFORMANCE')), name='insights_channel_obs_domain'),
        ),
        migrations.AddConstraint(
            model_name='channelperformanceobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('availability_state', 'PRESENT'), ('numeric_value__isnull', False)), models.Q(models.Q(('availability_state', 'PRESENT'), _negated=True), ('numeric_value__isnull', True)), _connector='OR'), name='insights_channel_obs_availability'),
        ),
        migrations.AddConstraint(
            model_name='publicationperformanceobservation',
            constraint=models.CheckConstraint(condition=models.Q(('data_domain', 'CONTENT_PERFORMANCE')), name='insights_publication_obs_domain'),
        ),
        migrations.AddConstraint(
            model_name='publicationperformanceobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('availability_state', 'PRESENT'), ('numeric_value__isnull', False)), models.Q(models.Q(('availability_state', 'PRESENT'), _negated=True), ('numeric_value__isnull', True)), _connector='OR'), name='insights_publication_obs_availability'),
        ),
        migrations.AddConstraint(
            model_name='searchproperty',
            constraint=models.UniqueConstraint(fields=('provider', 'property_key'), name='insights_unique_search_property'),
        ),
        migrations.AddConstraint(
            model_name='searchindexobservation',
            constraint=models.CheckConstraint(condition=models.Q(('data_domain', 'SEARCH_VISIBILITY')), name='insights_search_index_domain'),
        ),
        migrations.AddConstraint(
            model_name='searchindexobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('availability_state', 'PRESENT'), ('numeric_value__isnull', False)), models.Q(models.Q(('availability_state', 'PRESENT'), _negated=True), ('numeric_value__isnull', True)), _connector='OR'), name='insights_search_index_availability'),
        ),
        migrations.AddConstraint(
            model_name='searchvisibilityobservation',
            constraint=models.CheckConstraint(condition=models.Q(('data_domain', 'SEARCH_VISIBILITY')), name='insights_search_visibility_domain'),
        ),
        migrations.AddConstraint(
            model_name='searchvisibilityobservation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('availability_state', 'PRESENT'), ('numeric_value__isnull', False)), models.Q(models.Q(('availability_state', 'PRESENT'), _negated=True), ('numeric_value__isnull', True)), _connector='OR'), name='insights_search_visibility_availability'),
        ),
        migrations.AddConstraint(
            model_name='learningevidencelink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('channel_performance__isnull', True), ('commerce__isnull', True), ('geo_metric__isnull', True), ('publication_performance__isnull', False), ('search_index__isnull', True), ('search_visibility__isnull', True), ('source_kind', 'PUBLICATION_PERFORMANCE')), models.Q(('channel_performance__isnull', False), ('commerce__isnull', True), ('geo_metric__isnull', True), ('publication_performance__isnull', True), ('search_index__isnull', True), ('search_visibility__isnull', True), ('source_kind', 'CHANNEL_PERFORMANCE')), models.Q(('channel_performance__isnull', True), ('commerce__isnull', True), ('geo_metric__isnull', True), ('publication_performance__isnull', True), ('search_index__isnull', True), ('search_visibility__isnull', False), ('source_kind', 'SEARCH_VISIBILITY')), models.Q(('channel_performance__isnull', True), ('commerce__isnull', True), ('geo_metric__isnull', True), ('publication_performance__isnull', True), ('search_index__isnull', False), ('search_visibility__isnull', True), ('source_kind', 'SEARCH_INDEX')), models.Q(('channel_performance__isnull', True), ('commerce__isnull', False), ('geo_metric__isnull', True), ('publication_performance__isnull', True), ('search_index__isnull', True), ('search_visibility__isnull', True), ('source_kind', 'COMMERCE')), models.Q(('channel_performance__isnull', True), ('commerce__isnull', True), ('geo_metric__isnull', False), ('publication_performance__isnull', True), ('search_index__isnull', True), ('search_visibility__isnull', True), ('source_kind', 'GEO')), _connector='OR'), name='insights_learning_evidence_typed_source'),
        ),
    ]
