# Generated by Django 5.2.15 on 2026-08-18 15:52

import core.ids
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('principal_type', models.CharField(choices=[('HUMAN_USER', 'Human user'), ('SERVICE_ACCOUNT', 'Service account'), ('API_CLIENT', 'API client'), ('SYSTEM', 'System')], default='HUMAN_USER', max_length=24)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('auth_provider', models.CharField(default='internal', max_length=64)),
                ('auth_subject', models.CharField(blank=True, max_length=255)),
                ('mfa_status', models.CharField(choices=[('NOT_ENROLLED', 'Not enrolled'), ('ENROLLED', 'Enrolled'), ('EXEMPT', 'Exempt')], default='NOT_ENROLLED', max_length=20)),
                ('principal_status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('LOCKED', 'Locked'), ('DECOMMISSIONED', 'Decommissioned')], default='ACTIVE', max_length=20)),
                ('decommissioned_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PermissionGrant',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_kind', models.CharField(choices=[('GLOBAL', 'Global'), ('PRODUCT', 'Product'), ('PLATFORM', 'Platform')], max_length=16)),
                ('platform_code', models.CharField(blank=True, max_length=64)),
                ('action', models.CharField(choices=[('VIEW', 'View'), ('EDIT', 'Edit'), ('REVIEW', 'Review'), ('APPROVE', 'Approve'), ('PUBLISH', 'Publish'), ('MANAGE_ACCOUNT', 'Manage account'), ('EMERGENCY_STOP', 'Emergency stop'), ('COLLECT_READ_ONLY', 'Collect read-only')], max_length=32)),
                ('effect', models.CharField(choices=[('ALLOW', 'Allow'), ('DENY', 'Deny')], default='ALLOW', max_length=8)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=16)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('grant_status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=16)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('granted_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants_issued', to=settings.AUTH_USER_MODEL)),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permission_grants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
