# Generated by Django 5.2.15 on 2026-08-18 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiongrant',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permission_grants', to='products.product'),
        ),
        migrations.AddField(
            model_name='permissiongrant',
            name='revoked_by_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grants_revoked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='principal',
            constraint=models.UniqueConstraint(condition=models.Q(('auth_subject', ''), _negated=True), fields=('auth_provider', 'auth_subject'), name='accounts_unique_provider_subject'),
        ),
        migrations.AddConstraint(
            model_name='permissiongrant',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='accounts_grant_valid_window'),
        ),
        migrations.AddConstraint(
            model_name='permissiongrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('platform_code', ''), ('product__isnull', True), ('scope_kind', 'GLOBAL')), models.Q(('platform_code', ''), ('product__isnull', False), ('scope_kind', 'PRODUCT')), models.Q(('product__isnull', True), ('scope_kind', 'PLATFORM'), models.Q(('platform_code', ''), _negated=True)), _connector='OR'), name='accounts_grant_explicit_scope'),
        ),
    ]
