# Generated by Django 5.2.15 on 2026-08-18 16:28

from django.db import migrations, models


def disable_non_active_principals(apps, schema_editor):
    Principal = apps.get_model("accounts", "Principal")
    Principal.objects.exclude(principal_status="ACTIVE").update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='permissiongrant',
            name='accounts_grant_explicit_scope',
        ),
        migrations.AddField(
            model_name='permissiongrant',
            name='account_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='permissiongrant',
            name='surface_ref',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='principal',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('OPERATIONS_ADMIN', 'Operations admin'), ('OPERATOR', 'Operator')], default='OPERATOR', max_length=24),
        ),
        migrations.AlterField(
            model_name='permissiongrant',
            name='scope_kind',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('PRODUCT', 'Product'), ('PLATFORM', 'Platform'), ('ACCOUNT', 'Account'), ('SURFACE', 'Surface')], max_length=16),
        ),
        migrations.AddConstraint(
            model_name='permissiongrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account_ref', ''), ('platform_code', ''), ('product__isnull', True), ('scope_kind', 'GLOBAL'), ('surface_ref', '')), models.Q(('account_ref', ''), ('platform_code', ''), ('product__isnull', False), ('scope_kind', 'PRODUCT'), ('surface_ref', '')), models.Q(('account_ref', ''), ('product__isnull', True), ('scope_kind', 'PLATFORM'), ('surface_ref', ''), models.Q(('platform_code', ''), _negated=True)), models.Q(('platform_code', ''), ('product__isnull', True), ('scope_kind', 'ACCOUNT'), ('surface_ref', ''), models.Q(('account_ref', ''), _negated=True)), models.Q(('account_ref', ''), ('platform_code', ''), ('product__isnull', True), ('scope_kind', 'SURFACE'), models.Q(('surface_ref', ''), _negated=True)), _connector='OR'), name='accounts_grant_explicit_scope'),
        ),
        migrations.RunPython(disable_non_active_principals, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='principal',
            constraint=models.CheckConstraint(condition=models.Q(('principal_status', 'ACTIVE'), ('is_active', False), _connector='OR'), name='accounts_inactive_status_cannot_login'),
        ),
    ]
