# Generated by Django 5.2.15 on 2026-08-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_permissiongrant_accounts_grant_explicit_scope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissiongrant',
            name='action',
            field=models.CharField(choices=[('VIEW', 'View'), ('EDIT', 'Edit'), ('CREATE_TASK', 'Create task'), ('ASSIGN_TASK', 'Assign task'), ('CANCEL_TASK', 'Cancel task'), ('COMPLETE_TASK', 'Complete task'), ('REVIEW', 'Review'), ('APPROVE', 'Approve'), ('PUBLISH', 'Publish'), ('MANAGE_ACCOUNT', 'Manage account'), ('EMERGENCY_STOP', 'Emergency stop'), ('COLLECT_READ_ONLY', 'Collect read-only')], max_length=32),
        ),
    ]
