# Generated by Django 5.2.15 on 2026-08-21 09:05

import core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_permissiongrant_action'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretReference',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('secret_key', models.CharField(max_length=120)),
                ('provider_code', models.CharField(max_length=64)),
                ('backend', models.CharField(choices=[('FILE_MOUNT', 'Read-only file mount'), ('EXTERNAL_MANAGER', 'External secret manager')], max_length=24)),
                ('reference_name', models.CharField(help_text='Environment variable base name or external secret identifier; never the value.', max_length=255)),
                ('environment_scope', models.CharField(choices=[('LOCAL', 'Local'), ('STAGING', 'Staging'), ('PRODUCTION', 'Production')], max_length=16)),
                ('purpose', models.CharField(max_length=240)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ROTATION_REQUIRED', 'Rotation required'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=24)),
                ('last_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='permissiongrant',
            name='supersedes_grant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='renewed_by_grant', to='accounts.permissiongrant'),
        ),
        migrations.AddField(
            model_name='principal',
            name='must_change_password',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='permissiongrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('grant_status', 'REVOKED'), ('revoked_at__isnull', False), ('revoked_by_principal__isnull', False), models.Q(('revocation_reason', ''), _negated=True)), models.Q(models.Q(('grant_status', 'REVOKED'), _negated=True), ('revocation_reason', ''), ('revoked_at__isnull', True), ('revoked_by_principal__isnull', True)), _connector='OR'), name='accounts_grant_revocation_metadata'),
        ),
        migrations.AddField(
            model_name='secretreference',
            name='created_by_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secret_references_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='secretreference',
            name='updated_by_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secret_references_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='secretreference',
            constraint=models.UniqueConstraint(fields=('secret_key', 'environment_scope'), name='accounts_unique_secret_reference_scope'),
        ),
        migrations.AddConstraint(
            model_name='secretreference',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('last_rotated_at__isnull', True), ('expires_at__gt', models.F('last_rotated_at')), _connector='OR'), name='accounts_secret_expiry_after_rotation'),
        ),
    ]
