# Generated by Django 5.2.15 on 2026-08-18 16:14

import core.ids
import django.db.models.deletion
import django.utils.timezone
import releasegate.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('contentops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseGateEvaluationLink',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RuleEvaluationResult',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('rule_code', models.CharField(max_length=100)),
                ('required', models.BooleanField(default=True)),
                ('result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('BLOCKED', 'Blocked'), ('ERROR', 'Error'), ('SKIPPED', 'Skipped'), ('UNKNOWN', 'Unknown')], max_length=16)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('evidence_reference', models.CharField(blank=True, max_length=1024)),
                ('evidence_sha256', models.CharField(blank=True, max_length=64, validators=[releasegate.models.validate_sha256])),
                ('command_id', models.UUIDField(unique=True)),
                ('payload_hash', models.CharField(max_length=64, validators=[releasegate.models.validate_sha256])),
                ('evaluated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RuleEvaluationRun',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed')], default='RUNNING', max_length=16)),
                ('outcome', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('PASSED', 'Passed'), ('BLOCKED', 'Blocked')], default='UNKNOWN', max_length=16)),
                ('policy_version_ids', models.JSONField()),
                ('policy_set_sha256', models.CharField(max_length=64, validators=[releasegate.models.validate_sha256])),
                ('context_sha256', models.CharField(max_length=64, validators=[releasegate.models.validate_sha256])),
                ('expected_result_count', models.PositiveIntegerField()),
                ('actual_result_count', models.PositiveIntegerField(default=0)),
                ('evaluator_key', models.CharField(max_length=100)),
                ('command_id', models.UUIDField(unique=True)),
                ('payload_hash', models.CharField(max_length=64, validators=[releasegate.models.validate_sha256])),
                ('initiated_by_acting_role', models.CharField(choices=[('OWNER', 'Owner'), ('OPERATIONS_ADMIN', 'Operations admin'), ('OPERATOR', 'Operator')], max_length=24)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RuntimeEnvironment',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment_code', models.CharField(max_length=100, unique=True)),
                ('environment_type', models.CharField(choices=[('STAGING', 'Staging'), ('PRODUCTION', 'Production')], max_length=16)),
                ('identity_namespace', models.CharField(max_length=255)),
                ('database_namespace', models.CharField(max_length=255)),
                ('object_storage_namespace', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('LOCKED', 'Locked'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountEnvironmentBinding',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('binding_version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOKED', 'Revoked'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=16)),
                ('identity_reference', models.CharField(max_length=255)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='releasegate.accountenvironmentbinding')),
            ],
        ),
        migrations.CreateModel(
            name='CapabilityState',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('capability_code', models.CharField(default='MANUAL_PUBLISH', max_length=64)),
                ('state_version', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('UNKNOWN', 'Unknown')], max_length=16)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('evidence_reference', models.CharField(blank=True, max_length=1024)),
                ('evidence_sha256', models.CharField(blank=True, max_length=64, validators=[releasegate.models.validate_sha256])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_environment_binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capability_states', to='releasegate.accountenvironmentbinding')),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='releasegate.capabilitystate')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelAccount',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_code', models.CharField(max_length=64)),
                ('account_code', models.CharField(max_length=100, unique=True)),
                ('external_account_ref', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=240)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=16)),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channel_accounts_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='channel_accounts_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='accountenvironmentbinding',
            name='channel_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='environment_bindings', to='releasegate.channelaccount'),
        ),
        migrations.CreateModel(
            name='PolicyDefinition',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=16)),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_definitions_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_definitions_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['policy_code'],
            },
        ),
        migrations.CreateModel(
            name='PolicyVersion',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('rules', models.JSONField()),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('manifest_sha256', models.CharField(blank=True, max_length=64, validators=[releasegate.models.validate_sha256])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_versions_created', to=settings.AUTH_USER_MODEL)),
                ('policy_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='releasegate.policydefinition')),
                ('recorded_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_versions_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['policy_definition_id', 'version_number'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('GATE_PENDING', 'Gate pending'), ('GATE_BLOCKED', 'Gate blocked'), ('READY_FOR_MANUAL_PUBLISH', 'Ready for manual publish'), ('MANUAL_PUBLISHED_RECORDED', 'Manual publication recorded')], default='GATE_PENDING', max_length=32)),
                ('state_version', models.PositiveIntegerField(default=0)),
                ('creation_command_id', models.UUIDField(unique=True)),
                ('creation_payload_hash', models.CharField(max_length=64, validators=[releasegate.models.validate_sha256])),
                ('requested_by_acting_role', models.CharField(choices=[('OWNER', 'Owner'), ('OPERATIONS_ADMIN', 'Operations admin'), ('OPERATOR', 'Operator')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_under_grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.permissiongrant')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='contentops.tasksubmission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicationEvent',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('GATE_PENDING', 'Gate pending'), ('GATE_BLOCKED', 'Gate blocked'), ('READY_FOR_MANUAL_PUBLISH', 'Ready for manual publish'), ('MANUAL_PUBLISHED_RECORDED', 'Manual publication recorded')], max_length=32)),
                ('event_sequence', models.PositiveIntegerField()),
                ('expected_state_version', models.PositiveIntegerField()),
                ('resulting_state_version', models.PositiveIntegerField()),
                ('command_id', models.UUIDField(unique=True)),
                ('payload_hash', models.CharField(max_length=64, validators=[releasegate.models.validate_sha256])),
                ('acting_role', models.CharField(choices=[('OWNER', 'Owner'), ('OPERATIONS_ADMIN', 'Operations admin'), ('OPERATOR', 'Operator')], max_length=24)),
                ('external_publication_id', models.CharField(blank=True, max_length=255)),
                ('external_url', models.URLField(blank=True, max_length=1024)),
                ('proof_reference', models.CharField(blank=True, max_length=1024)),
                ('proof_sha256', models.CharField(blank=True, max_length=64, validators=[releasegate.models.validate_sha256])),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('permission_grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.permissiongrant')),
                ('previous_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_event', to='releasegate.publicationevent')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='releasegate.publication')),
                ('recorded_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['publication_id', 'event_sequence'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseGateRecord',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('policy_set_sha256', models.CharField(max_length=64, validators=[releasegate.models.validate_sha256])),
                ('context_sha256', models.CharField(max_length=64, validators=[releasegate.models.validate_sha256])),
                ('outcome', models.CharField(choices=[('PASSED', 'Passed'), ('BLOCKED', 'Blocked')], max_length=16)),
                ('failure_reasons', models.JSONField(default=list)),
                ('result_count', models.PositiveIntegerField()),
                ('valid_until', models.DateTimeField()),
                ('command_id', models.UUIDField(unique=True)),
                ('payload_hash', models.CharField(max_length=64, validators=[releasegate.models.validate_sha256])),
                ('evaluated_by_acting_role', models.CharField(choices=[('OWNER', 'Owner'), ('OPERATIONS_ADMIN', 'Operations admin'), ('OPERATOR', 'Operator')], max_length=24)),
                ('evaluated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_environment_binding', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_records', to='releasegate.accountenvironmentbinding')),
                ('capability_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_records', to='releasegate.capabilitystate')),
                ('channel_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_records', to='releasegate.channelaccount')),
                ('evaluated_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('primary_asset_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_records', to='contentops.contentassetversion')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_records', to='releasegate.publication')),
                ('publisher_grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.permissiongrant')),
                ('publisher_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('review_decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_records', to='contentops.reviewdecision')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
