# Generated by Django 5.2.15 on 2026-08-18 16:14

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('contentops', '0002_initial'),
        ('releasegate', '0001_initial'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='releasegaterecord',
            name='task_contract_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_records', to='workflow.taskcontractversion'),
        ),
        migrations.AddField(
            model_name='releasegaterecord',
            name='task_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_records', to='contentops.tasksubmission'),
        ),
        migrations.AddField(
            model_name='releasegateevaluationlink',
            name='gate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_links', to='releasegate.releasegaterecord'),
        ),
        migrations.AddField(
            model_name='publicationevent',
            name='release_gate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publication_events', to='releasegate.releasegaterecord'),
        ),
        migrations.AddField(
            model_name='publication',
            name='current_gate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_publications', to='releasegate.releasegaterecord'),
        ),
        migrations.AddField(
            model_name='ruleevaluationresult',
            name='evaluated_by_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ruleevaluationresult',
            name='policy_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_results', to='releasegate.policyversion'),
        ),
        migrations.AddField(
            model_name='ruleevaluationresult',
            name='recorded_by_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='releasegateevaluationlink',
            name='evaluation_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gate_link', to='releasegate.ruleevaluationresult'),
        ),
        migrations.AddField(
            model_name='ruleevaluationrun',
            name='initiated_by_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ruleevaluationrun',
            name='initiated_under_grant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.permissiongrant'),
        ),
        migrations.AddField(
            model_name='ruleevaluationrun',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_runs', to='releasegate.publication'),
        ),
        migrations.AddField(
            model_name='ruleevaluationrun',
            name='recorded_by_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ruleevaluationresult',
            name='evaluation_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='releasegate.ruleevaluationrun'),
        ),
        migrations.AddField(
            model_name='releasegaterecord',
            name='evaluation_run',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gate_record', to='releasegate.ruleevaluationrun'),
        ),
        migrations.AddField(
            model_name='runtimeenvironment',
            name='created_by_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runtime_environments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='runtimeenvironment',
            name='updated_by_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runtime_environments_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='releasegaterecord',
            name='runtime_environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gate_records', to='releasegate.runtimeenvironment'),
        ),
        migrations.AddField(
            model_name='accountenvironmentbinding',
            name='runtime_environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_bindings', to='releasegate.runtimeenvironment'),
        ),
        migrations.AddConstraint(
            model_name='capabilitystate',
            constraint=models.UniqueConstraint(fields=('account_environment_binding', 'capability_code', 'state_version'), name='releasegate_unique_capability_state_version'),
        ),
        migrations.AddConstraint(
            model_name='capabilitystate',
            constraint=models.CheckConstraint(condition=models.Q(('state_version__gte', 1)), name='releasegate_capability_version_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='capabilitystate',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('expires_at__gt', models.F('effective_from')), _connector='OR'), name='releasegate_capability_valid_window'),
        ),
        migrations.AddConstraint(
            model_name='channelaccount',
            constraint=models.UniqueConstraint(fields=('platform_code', 'external_account_ref'), name='releasegate_unique_platform_account'),
        ),
        migrations.AddConstraint(
            model_name='policydefinition',
            constraint=models.CheckConstraint(condition=models.Q(('policy_code', ''), _negated=True), name='releasegate_policy_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='policyversion',
            constraint=models.UniqueConstraint(fields=('policy_definition', 'version_number'), name='releasegate_unique_policy_version'),
        ),
        migrations.AddConstraint(
            model_name='policyversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gte', 1)), name='releasegate_policy_version_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='policyversion',
            constraint=models.CheckConstraint(condition=models.Q(('effective_until__isnull', True), ('effective_until__gt', models.F('effective_from')), _connector='OR'), name='releasegate_policy_effective_window'),
        ),
        migrations.AddConstraint(
            model_name='publicationevent',
            constraint=models.UniqueConstraint(fields=('publication', 'event_sequence'), name='releasegate_unique_publication_event_sequence'),
        ),
        migrations.AddConstraint(
            model_name='publicationevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_sequence__gte', 1)), name='releasegate_event_sequence_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='publicationevent',
            constraint=models.CheckConstraint(condition=models.Q(('resulting_state_version', django.db.models.expressions.CombinedExpression(models.F('expected_state_version'), '+', models.Value(1)))), name='releasegate_event_advances_one_version'),
        ),
        migrations.AddConstraint(
            model_name='ruleevaluationresult',
            constraint=models.UniqueConstraint(fields=('evaluation_run', 'policy_version', 'rule_code'), name='releasegate_unique_rule_result'),
        ),
        migrations.AddConstraint(
            model_name='accountenvironmentbinding',
            constraint=models.UniqueConstraint(fields=('channel_account', 'runtime_environment', 'binding_version'), name='releasegate_unique_binding_version'),
        ),
        migrations.AddConstraint(
            model_name='accountenvironmentbinding',
            constraint=models.CheckConstraint(condition=models.Q(('binding_version__gte', 1)), name='releasegate_binding_version_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='accountenvironmentbinding',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='releasegate_binding_valid_window'),
        ),
    ]
