# Generated by Django 5.2.15 on 2026-08-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releasegate', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasegaterecord',
            name='failure_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
