# Generated by Django 5.2.15 on 2026-08-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releasegate', '0003_alter_releasegaterecord_failure_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='requested_by_acting_role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('OPERATIONS_ADMIN', 'Operations admin'), ('OPERATOR', 'Operator'), ('SYSTEM', 'System')], max_length=24),
        ),
        migrations.AlterField(
            model_name='publicationevent',
            name='acting_role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('OPERATIONS_ADMIN', 'Operations admin'), ('OPERATOR', 'Operator'), ('SYSTEM', 'System')], max_length=24),
        ),
        migrations.AlterField(
            model_name='releasegaterecord',
            name='evaluated_by_acting_role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('OPERATIONS_ADMIN', 'Operations admin'), ('OPERATOR', 'Operator'), ('SYSTEM', 'System')], max_length=24),
        ),
        migrations.AlterField(
            model_name='ruleevaluationrun',
            name='initiated_by_acting_role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('OPERATIONS_ADMIN', 'Operations admin'), ('OPERATOR', 'Operator'), ('SYSTEM', 'System')], max_length=24),
        ),
    ]
