# Generated by Django 5.2.15 on 2026-08-21 09:05

import core.ids
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_secretreference_permissiongrant_supersedes_grant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueSourceLink',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('source_kind', models.CharField(choices=[('TASK', 'Task'), ('PUBLICATION', 'Publication'), ('METRIC_COLLECTION_RUN', 'Metric collection run'), ('GEO_PROBE_RUN', 'GEO probe run'), ('MANUAL', 'Manual')], max_length=32)),
                ('source_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('meeting_key', models.CharField(max_length=160, unique=True)),
                ('meeting_type', models.CharField(choices=[('OPERATIONAL_REVIEW', 'Operational review'), ('RULE_GOVERNANCE', 'Rule governance'), ('SAFETY_INCIDENT', 'Safety incident')], max_length=32)),
                ('title', models.CharField(max_length=240)),
                ('summary', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingDecision',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('decision_key', models.CharField(max_length=160)),
                ('decision_type', models.CharField(choices=[('RULE_PROPOSAL', 'Rule proposal'), ('OPERATIONAL_FIX', 'Operational fix'), ('NO_ACTION', 'No action')], max_length=24)),
                ('decision', models.TextField()),
                ('impact_scope', models.JSONField(blank=True, default=dict)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('participant_role', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyActivation',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('activation_scope', models.JSONField(blank=True, default=dict)),
                ('effective_from', models.DateTimeField()),
                ('acting_role', models.CharField(choices=[('OWNER', 'Owner'), ('OPERATIONS_ADMIN', 'Operations admin'), ('OPERATOR', 'Operator'), ('SYSTEM', 'System')], max_length=24)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PolicyActivationEvent',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('ACTIVATED', 'Activated'), ('MONITORING', 'Monitoring'), ('SUPERSEDED', 'Superseded'), ('ROLLED_BACK', 'Rolled back')], max_length=16)),
                ('event_sequence', models.PositiveIntegerField()),
                ('command_id', models.UUIDField(unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('reason', models.TextField(blank=True)),
                ('acting_role', models.CharField(choices=[('OWNER', 'Owner'), ('OPERATIONS_ADMIN', 'Operations admin'), ('OPERATOR', 'Operator'), ('SYSTEM', 'System')], max_length=24)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyRollbackEvent',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('acting_role', models.CharField(choices=[('OWNER', 'Owner'), ('OPERATIONS_ADMIN', 'Operations admin'), ('OPERATOR', 'Operator'), ('SYSTEM', 'System')], max_length=24)),
                ('rollback_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RuleApprovalDecision',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CHANGES_REQUESTED', 'Changes requested')], max_length=24)),
                ('acting_role', models.CharField(choices=[('OWNER', 'Owner'), ('OPERATIONS_ADMIN', 'Operations admin'), ('OPERATOR', 'Operator'), ('SYSTEM', 'System')], max_length=24)),
                ('rationale', models.TextField()),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RuleProposalSourceLink',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('source_kind', models.CharField(choices=[('MEETING_DECISION', 'Meeting decision'), ('LEARNING', 'Learning'), ('ISSUE', 'Issue'), ('OFFICIAL_POLICY', 'Official policy'), ('MANUAL', 'Manual')], max_length=24)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RuleProposalVersion',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('proposal_key', models.CharField(max_length=160)),
                ('version_number', models.PositiveIntegerField()),
                ('change_effect', models.CharField(choices=[('TIGHTEN', 'Tighten'), ('RELAX', 'Relax'), ('CLARIFY', 'Clarify'), ('ADD', 'Add'), ('RETIRE', 'Retire')], max_length=16)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=16)),
                ('affected_scope', models.JSONField(blank=True, default=dict)),
                ('rationale', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RuleValidationRun',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('validation_type', models.CharField(choices=[('HISTORICAL_REPLAY', 'Historical replay'), ('SHADOW', 'Shadow'), ('CANARY', 'Canary')], max_length=24)),
                ('input_version_hash', models.CharField(max_length=64)),
                ('data_window_start', models.DateTimeField()),
                ('data_window_end', models.DateTimeField()),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('result', models.CharField(choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial'), ('ERROR', 'Error')], max_length=16)),
                ('false_positive_count', models.PositiveIntegerField(default=0)),
                ('false_negative_count', models.PositiveIntegerField(default=0)),
                ('risk_events', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('issue_key', models.CharField(max_length=160, unique=True)),
                ('issue_type', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('BLOCKER', 'Blocker'), ('SAFETY_EVENT', 'Safety event'), ('RULE_CONFLICT', 'Rule conflict')], max_length=24)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=16)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('current_state', models.CharField(choices=[('OPEN', 'Open'), ('TRIAGED', 'Triaged'), ('IN_PROGRESS', 'In progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('ESCALATED_TO_MEETING', 'Escalated to meeting')], default='OPEN', max_length=32)),
                ('state_version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IssueDecisionLink',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('linkage_role', models.CharField(choices=[('PRIMARY', 'Primary'), ('RELATED', 'Related')], max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision_links', to='governance.issue')),
            ],
        ),
        migrations.CreateModel(
            name='IssueEvent',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('from_state', models.CharField(choices=[('OPEN', 'Open'), ('TRIAGED', 'Triaged'), ('IN_PROGRESS', 'In progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('ESCALATED_TO_MEETING', 'Escalated to meeting')], max_length=32)),
                ('to_state', models.CharField(choices=[('OPEN', 'Open'), ('TRIAGED', 'Triaged'), ('IN_PROGRESS', 'In progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('ESCALATED_TO_MEETING', 'Escalated to meeting')], max_length=32)),
                ('event_sequence', models.PositiveIntegerField()),
                ('expected_state_version', models.PositiveIntegerField()),
                ('resulting_state_version', models.PositiveIntegerField()),
                ('command_id', models.UUIDField(unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('reason', models.TextField()),
                ('acting_role', models.CharField(choices=[('OWNER', 'Owner'), ('OPERATIONS_ADMIN', 'Operations admin'), ('OPERATOR', 'Operator'), ('SYSTEM', 'System')], max_length=24)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='governance.issue')),
                ('permission_grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.permissiongrant')),
            ],
        ),
    ]
