# Generated by Django 5.2.15 on 2026-08-21 09:05

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_secretreference_permissiongrant_supersedes_grant_and_more'),
        ('governance', '0001_initial'),
        ('insights', '0001_initial'),
        ('releasegate', '0004_alter_publication_requested_by_acting_role_and_more'),
        ('workflow', '0003_task_creation_command_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issuesourcelink',
            name='geo_probe_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issue_links', to='insights.geoproberun'),
        ),
        migrations.AddField(
            model_name='issuesourcelink',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_links', to='governance.issue'),
        ),
        migrations.AddField(
            model_name='issuesourcelink',
            name='metric_collection_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issue_links', to='insights.metriccollectionrun'),
        ),
        migrations.AddField(
            model_name='issuesourcelink',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issue_links', to='releasegate.publication'),
        ),
        migrations.AddField(
            model_name='issuesourcelink',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issue_links', to='workflow.task'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='created_by_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingdecision',
            name='created_by_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingdecision',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='governance.meeting'),
        ),
        migrations.AddField(
            model_name='meetingdecision',
            name='owner_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_decisions_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issuedecisionlink',
            name='meeting_decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_links', to='governance.meetingdecision'),
        ),
        migrations.AddField(
            model_name='meetingparticipant',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='governance.meeting'),
        ),
        migrations.AddField(
            model_name='meetingparticipant',
            name='principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meeting_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyactivation',
            name='activated_by_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyactivation',
            name='permission_grant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.permissiongrant'),
        ),
        migrations.AddField(
            model_name='policyactivation',
            name='policy_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='governance_activations', to='releasegate.policyversion'),
        ),
        migrations.AddField(
            model_name='policyactivationevent',
            name='actor_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyactivationevent',
            name='permission_grant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.permissiongrant'),
        ),
        migrations.AddField(
            model_name='policyactivationevent',
            name='policy_activation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='governance.policyactivation'),
        ),
        migrations.AddField(
            model_name='policyactivationevent',
            name='previous_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_event', to='governance.policyactivationevent'),
        ),
        migrations.AddField(
            model_name='policyrollbackevent',
            name='activation_event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rollback_detail', to='governance.policyactivationevent'),
        ),
        migrations.AddField(
            model_name='policyrollbackevent',
            name='permission_grant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounts.permissiongrant'),
        ),
        migrations.AddField(
            model_name='policyrollbackevent',
            name='policy_activation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rollback_event', to='governance.policyactivation'),
        ),
        migrations.AddField(
            model_name='policyrollbackevent',
            name='rollback_by_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyrollbackevent',
            name='rollback_to_policy_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rollback_targets', to='releasegate.policyversion'),
        ),
        migrations.AddField(
            model_name='ruleapprovaldecision',
            name='approver_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_approval_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ruleapprovaldecision',
            name='permission_grant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_approval_decisions', to='accounts.permissiongrant'),
        ),
        migrations.AddField(
            model_name='ruleproposalsourcelink',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rule_proposal_links', to='governance.issue'),
        ),
        migrations.AddField(
            model_name='ruleproposalsourcelink',
            name='learning_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rule_proposal_links', to='insights.learningversion'),
        ),
        migrations.AddField(
            model_name='ruleproposalsourcelink',
            name='meeting_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rule_proposal_links', to='governance.meetingdecision'),
        ),
        migrations.AddField(
            model_name='ruleproposalsourcelink',
            name='official_policy_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proposal_source_links', to='releasegate.policyversion'),
        ),
        migrations.AddField(
            model_name='ruleproposalversion',
            name='candidate_policy_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_proposals', to='releasegate.policyversion'),
        ),
        migrations.AddField(
            model_name='ruleproposalversion',
            name='created_by_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ruleproposalversion',
            name='supersedes_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_version', to='governance.ruleproposalversion'),
        ),
        migrations.AddField(
            model_name='ruleproposalversion',
            name='target_policy_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_proposal_versions', to='releasegate.policydefinition'),
        ),
        migrations.AddField(
            model_name='ruleproposalsourcelink',
            name='rule_proposal_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_links', to='governance.ruleproposalversion'),
        ),
        migrations.AddField(
            model_name='ruleapprovaldecision',
            name='rule_proposal_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_decisions', to='governance.ruleproposalversion'),
        ),
        migrations.AddField(
            model_name='policyactivation',
            name='rule_proposal_version',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='policy_activation', to='governance.ruleproposalversion'),
        ),
        migrations.AddField(
            model_name='rulevalidationrun',
            name='created_by_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rulevalidationrun',
            name='policy_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='governance_validation_runs', to='releasegate.policyversion'),
        ),
        migrations.AddField(
            model_name='rulevalidationrun',
            name='rule_proposal_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validation_runs', to='governance.ruleproposalversion'),
        ),
        migrations.AddConstraint(
            model_name='issueevent',
            constraint=models.UniqueConstraint(fields=('issue', 'event_sequence'), name='governance_unique_issue_event_sequence'),
        ),
        migrations.AddConstraint(
            model_name='issueevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_sequence__gte', 1)), name='governance_issue_event_sequence_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='issueevent',
            constraint=models.CheckConstraint(condition=models.Q(('resulting_state_version', django.db.models.expressions.CombinedExpression(models.F('expected_state_version'), '+', models.Value(1)))), name='governance_issue_event_advances_one'),
        ),
        migrations.AddConstraint(
            model_name='issuesourcelink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('geo_probe_run__isnull', True), ('metric_collection_run__isnull', True), ('publication__isnull', True), ('source_kind', 'TASK'), ('task__isnull', False)), models.Q(('geo_probe_run__isnull', True), ('metric_collection_run__isnull', True), ('publication__isnull', False), ('source_kind', 'PUBLICATION'), ('task__isnull', True)), models.Q(('geo_probe_run__isnull', True), ('metric_collection_run__isnull', False), ('publication__isnull', True), ('source_kind', 'METRIC_COLLECTION_RUN'), ('task__isnull', True)), models.Q(('geo_probe_run__isnull', False), ('metric_collection_run__isnull', True), ('publication__isnull', True), ('source_kind', 'GEO_PROBE_RUN'), ('task__isnull', True)), models.Q(('geo_probe_run__isnull', True), ('metric_collection_run__isnull', True), ('publication__isnull', True), ('source_kind', 'MANUAL'), ('task__isnull', True)), _connector='OR'), name='governance_issue_typed_source'),
        ),
        migrations.AddConstraint(
            model_name='meetingdecision',
            constraint=models.UniqueConstraint(fields=('meeting', 'decision_key'), name='governance_unique_meeting_decision'),
        ),
        migrations.AddConstraint(
            model_name='issuedecisionlink',
            constraint=models.UniqueConstraint(fields=('issue', 'meeting_decision'), name='governance_unique_issue_decision_link'),
        ),
        migrations.AddConstraint(
            model_name='meetingparticipant',
            constraint=models.UniqueConstraint(fields=('meeting', 'principal'), name='governance_unique_meeting_participant'),
        ),
        migrations.AddConstraint(
            model_name='policyactivationevent',
            constraint=models.UniqueConstraint(fields=('policy_activation', 'event_sequence'), name='governance_unique_activation_event_sequence'),
        ),
        migrations.AddConstraint(
            model_name='policyactivationevent',
            constraint=models.CheckConstraint(condition=models.Q(('event_sequence__gte', 1)), name='governance_activation_event_sequence_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='ruleproposalversion',
            constraint=models.UniqueConstraint(fields=('proposal_key', 'version_number'), name='governance_unique_rule_proposal_version'),
        ),
        migrations.AddConstraint(
            model_name='ruleproposalversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gte', 1)), name='governance_rule_proposal_version_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='ruleproposalsourcelink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('issue__isnull', True), ('learning_version__isnull', True), ('meeting_decision__isnull', False), ('official_policy_version__isnull', True), ('source_kind', 'MEETING_DECISION')), models.Q(('issue__isnull', True), ('learning_version__isnull', False), ('meeting_decision__isnull', True), ('official_policy_version__isnull', True), ('source_kind', 'LEARNING')), models.Q(('issue__isnull', False), ('learning_version__isnull', True), ('meeting_decision__isnull', True), ('official_policy_version__isnull', True), ('source_kind', 'ISSUE')), models.Q(('issue__isnull', True), ('learning_version__isnull', True), ('meeting_decision__isnull', True), ('official_policy_version__isnull', False), ('source_kind', 'OFFICIAL_POLICY')), models.Q(('issue__isnull', True), ('learning_version__isnull', True), ('meeting_decision__isnull', True), ('official_policy_version__isnull', True), ('source_kind', 'MANUAL')), _connector='OR'), name='governance_rule_proposal_typed_source'),
        ),
        migrations.AddConstraint(
            model_name='rulevalidationrun',
            constraint=models.UniqueConstraint(fields=('rule_proposal_version', 'validation_type', 'input_version_hash'), name='governance_unique_validation_input'),
        ),
        migrations.AddConstraint(
            model_name='rulevalidationrun',
            constraint=models.CheckConstraint(condition=models.Q(('data_window_end__gt', models.F('data_window_start'))), name='governance_validation_window_valid'),
        ),
        migrations.AddConstraint(
            model_name='rulevalidationrun',
            constraint=models.CheckConstraint(condition=models.Q(('completed_at__gte', models.F('started_at'))), name='governance_validation_time_valid'),
        ),
    ]
