# Generated by Django 5.2.15 on 2026-08-18 16:14

import core.ids
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('products', '0001_initial'),
        ('releasegate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('current_state', models.CharField(choices=[('DRAFT', 'Draft'), ('BLOCKED', 'Blocked'), ('READY', 'Ready'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In progress'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('HUMAN_REWORK', 'Human rework'), ('APPROVED', 'Approved'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=24)),
                ('state_version', models.PositiveIntegerField(default=0)),
                ('blocked_from_state', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('BLOCKED', 'Blocked'), ('READY', 'Ready'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In progress'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('HUMAN_REWORK', 'Human rework'), ('APPROVED', 'Approved'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], max_length=24)),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks_created', to=settings.AUTH_USER_MODEL)),
                ('current_assignee_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='currently_assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='products.product')),
                ('product_profile_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='products.productprofileversion')),
                ('updated_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskContractVersion',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=240)),
                ('dor_criteria', models.JSONField(default=list)),
                ('dod_criteria', models.JSONField(default=list)),
                ('release_gate_criteria', models.JSONField(default=list)),
                ('success_criteria', models.JSONField(default=list)),
                ('manifest_sha256', models.CharField(blank=True, max_length=64)),
                ('sealed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_contract_versions_created', to=settings.AUTH_USER_MODEL)),
                ('product_profile_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_contract_versions', to='products.productprofileversion')),
            ],
        ),
        migrations.CreateModel(
            name='TaskContractPolicyLink',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_contract_policy_links_created', to=settings.AUTH_USER_MODEL)),
                ('policy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_contract_links', to='releasegate.policyversion')),
                ('task_contract_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_links', to='workflow.taskcontractversion')),
            ],
        ),
        migrations.CreateModel(
            name='TaskCheckRun',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('check_kind', models.CharField(choices=[('DOR', 'Definition of Ready'), ('DOD', 'Definition of Done')], max_length=8)),
                ('attempt_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed')], default='COMPLETED', max_length=16)),
                ('aggregate_result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('BLOCKED', 'Blocked'), ('ERROR', 'Error')], max_length=16)),
                ('expected_criterion_count', models.PositiveIntegerField()),
                ('actual_criterion_count', models.PositiveIntegerField()),
                ('context_sha256', models.CharField(max_length=64)),
                ('command_id', models.UUIDField(unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('evaluator_acting_role', models.CharField(choices=[('OWNER', 'Owner'), ('OPERATIONS_ADMIN', 'Operations admin'), ('OPERATOR', 'Operator'), ('SYSTEM', 'System')], max_length=24)),
                ('completed_at', models.DateTimeField()),
                ('evaluator_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_checks_evaluated', to=settings.AUTH_USER_MODEL)),
                ('permission_grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_check_runs', to='accounts.permissiongrant')),
                ('recorded_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_checks_recorded', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_runs', to='workflow.task')),
                ('contract_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='check_runs', to='workflow.taskcontractversion')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='contract_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='workflow.taskcontractversion'),
        ),
        migrations.CreateModel(
            name='TaskStateEvent',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('from_state', models.CharField(choices=[('DRAFT', 'Draft'), ('BLOCKED', 'Blocked'), ('READY', 'Ready'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In progress'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('HUMAN_REWORK', 'Human rework'), ('APPROVED', 'Approved'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], max_length=24)),
                ('to_state', models.CharField(choices=[('DRAFT', 'Draft'), ('BLOCKED', 'Blocked'), ('READY', 'Ready'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In progress'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('HUMAN_REWORK', 'Human rework'), ('APPROVED', 'Approved'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], max_length=24)),
                ('command_id', models.UUIDField(unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('expected_state_version', models.PositiveIntegerField()),
                ('resulting_state_version', models.PositiveIntegerField()),
                ('event_sequence', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('acting_role', models.CharField(choices=[('OWNER', 'Owner'), ('OPERATIONS_ADMIN', 'Operations admin'), ('OPERATOR', 'Operator'), ('SYSTEM', 'System')], max_length=24)),
                ('event_at', models.DateTimeField()),
                ('actor_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_state_events_acted', to=settings.AUTH_USER_MODEL)),
                ('permission_grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_state_events', to='accounts.permissiongrant')),
                ('previous_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_event', to='workflow.taskstateevent')),
                ('recorded_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_state_events_recorded', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='state_events', to='workflow.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('assignment_number', models.PositiveIntegerField()),
                ('command_id', models.UUIDField(unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('expected_task_version', models.PositiveIntegerField()),
                ('acting_role', models.CharField(choices=[('OWNER', 'Owner'), ('OPERATIONS_ADMIN', 'Operations admin'), ('OPERATOR', 'Operator'), ('SYSTEM', 'System')], max_length=24)),
                ('assigned_at', models.DateTimeField()),
                ('assigned_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assignee_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_assignments_received', to=settings.AUTH_USER_MODEL)),
                ('permission_grant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_assignments', to='accounts.permissiongrant')),
                ('recorded_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_assignments_recorded', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='workflow.task')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('task', 'assignment_number'), name='workflow_unique_assignment_number')],
            },
        ),
        migrations.CreateModel(
            name='TaskCheckResult',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('criterion_key', models.CharField(max_length=120)),
                ('criterion_sequence', models.PositiveIntegerField()),
                ('required', models.BooleanField(default=True)),
                ('result', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('BLOCKED', 'Blocked'), ('ERROR', 'Error')], max_length=16)),
                ('evidence', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField()),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_check_results_created', to=settings.AUTH_USER_MODEL)),
                ('check_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='workflow.taskcheckrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('check_run', 'criterion_key'), name='workflow_unique_check_criterion'), models.UniqueConstraint(fields=('check_run', 'criterion_sequence'), name='workflow_unique_check_sequence')],
            },
        ),
        migrations.AddConstraint(
            model_name='taskcontractversion',
            constraint=models.UniqueConstraint(fields=('product_profile_version', 'version_number'), name='workflow_unique_contract_version'),
        ),
        migrations.AddConstraint(
            model_name='taskcontractpolicylink',
            constraint=models.UniqueConstraint(fields=('task_contract_version', 'policy_version'), name='workflow_unique_contract_policy_link'),
        ),
        migrations.AddConstraint(
            model_name='taskcheckrun',
            constraint=models.UniqueConstraint(fields=('task', 'check_kind', 'attempt_number'), name='workflow_unique_check_attempt'),
        ),
        migrations.AddConstraint(
            model_name='taskcheckrun',
            constraint=models.CheckConstraint(condition=models.Q(('actual_criterion_count__lte', models.F('expected_criterion_count'))), name='workflow_check_actual_lte_expected'),
        ),
        migrations.AddConstraint(
            model_name='taskstateevent',
            constraint=models.UniqueConstraint(fields=('task', 'event_sequence'), name='workflow_unique_event_sequence'),
        ),
        migrations.AddConstraint(
            model_name='taskstateevent',
            constraint=models.UniqueConstraint(fields=('task', 'resulting_state_version'), name='workflow_unique_result_state_version'),
        ),
        migrations.AddConstraint(
            model_name='taskstateevent',
            constraint=models.CheckConstraint(condition=models.Q(('resulting_state_version', django.db.models.expressions.CombinedExpression(models.F('expected_state_version'), '+', models.Value(1)))), name='workflow_event_advances_one_version'),
        ),
    ]
