# Generated by Django 5.2.15 on 2026-08-19 16:56

import django.db.models.deletion
from django.db import migrations, models


def create_withdrawal_integrity_trigger(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "sqlite":
        for suffix, operation in (("insert", "INSERT"), ("update", "UPDATE")):
            schema_editor.execute(
                f"""
                CREATE TRIGGER workflow_withdrawal_task_match_{suffix}
                BEFORE {operation} ON workflow_taskstateevent
                WHEN NEW.event_type = 'SUBMISSION_WITHDRAWN'
                     AND NOT EXISTS (
                         SELECT 1
                         FROM contentops_tasksubmission submission
                         WHERE submission.id = NEW.submission_id
                           AND submission.task_id = NEW.task_id
                     )
                BEGIN
                    SELECT RAISE(ABORT, 'withdrawal submission belongs to another task');
                END;
                """
            )
        return
    if vendor == "postgresql":
        schema_editor.execute(
            """
            CREATE FUNCTION workflow_enforce_withdrawal_task_match() RETURNS trigger AS $$
            BEGIN
                IF NEW.event_type = 'SUBMISSION_WITHDRAWN' AND NOT EXISTS (
                    SELECT 1
                    FROM contentops_tasksubmission submission
                    WHERE submission.id = NEW.submission_id
                      AND submission.task_id = NEW.task_id
                ) THEN
                    RAISE EXCEPTION 'withdrawal submission belongs to another task'
                        USING ERRCODE = '23514';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """
        )
        schema_editor.execute(
            """
            CREATE TRIGGER workflow_withdrawal_task_match_guard
            BEFORE INSERT OR UPDATE ON workflow_taskstateevent
            FOR EACH ROW EXECUTE FUNCTION workflow_enforce_withdrawal_task_match();
            """
        )


def drop_withdrawal_integrity_trigger(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "sqlite":
        schema_editor.execute("DROP TRIGGER IF EXISTS workflow_withdrawal_task_match_insert;")
        schema_editor.execute("DROP TRIGGER IF EXISTS workflow_withdrawal_task_match_update;")
        return
    if vendor == "postgresql":
        schema_editor.execute(
            "DROP TRIGGER IF EXISTS workflow_withdrawal_task_match_guard ON workflow_taskstateevent;"
        )
        schema_editor.execute("DROP FUNCTION IF EXISTS workflow_enforce_withdrawal_task_match();")


class Migration(migrations.Migration):

    dependencies = [
        ('contentops', '0003_tasksubmission_contentops_submission_cannot_supersede_self'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstateevent',
            name='event_type',
            field=models.CharField(choices=[('STATE_TRANSITION', 'State transition'), ('SUBMISSION_WITHDRAWN', 'Submission withdrawn')], default='STATE_TRANSITION', max_length=32),
        ),
        migrations.AddField(
            model_name='taskstateevent',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_events', to='contentops.tasksubmission'),
        ),
        migrations.AddConstraint(
            model_name='taskstateevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_type', 'STATE_TRANSITION'), ('submission__isnull', True)), models.Q(('event_type', 'SUBMISSION_WITHDRAWN'), ('from_state', 'UNDER_REVIEW'), ('submission__isnull', False), ('to_state', 'IN_PROGRESS')), _connector='OR'), name='workflow_event_type_payload_shape'),
        ),
        migrations.AddConstraint(
            model_name='taskstateevent',
            constraint=models.UniqueConstraint(condition=models.Q(('event_type', 'SUBMISSION_WITHDRAWN')), fields=('submission',), name='workflow_one_withdrawal_per_submission'),
        ),
        migrations.RunPython(create_withdrawal_integrity_trigger, drop_withdrawal_integrity_trigger),
    ]
