# Generated by Django 5.2.15 on 2026-08-26 05:23

from django.conf import settings
from django.db import migrations, models


def _drop_submission_exit_integrity_trigger(schema_editor):
    vendor = schema_editor.connection.vendor
    if vendor == "sqlite":
        schema_editor.execute(
            "DROP TRIGGER IF EXISTS workflow_withdrawal_task_match_insert;"
        )
        schema_editor.execute(
            "DROP TRIGGER IF EXISTS workflow_withdrawal_task_match_update;"
        )
        return
    if vendor == "postgresql":
        schema_editor.execute(
            "DROP TRIGGER IF EXISTS workflow_withdrawal_task_match_guard "
            "ON workflow_taskstateevent;"
        )
        schema_editor.execute(
            "DROP FUNCTION IF EXISTS workflow_enforce_withdrawal_task_match();"
        )


def _create_submission_exit_integrity_trigger(schema_editor, *, include_abandonment):
    vendor = schema_editor.connection.vendor
    event_predicate = (
        "NEW.event_type IN ('SUBMISSION_WITHDRAWN', 'SUBMISSION_ABANDONED')"
        if include_abandonment
        else "NEW.event_type = 'SUBMISSION_WITHDRAWN'"
    )
    if vendor == "sqlite":
        for suffix, operation in (("insert", "INSERT"), ("update", "UPDATE")):
            schema_editor.execute(
                f"""
                CREATE TRIGGER workflow_withdrawal_task_match_{suffix}
                BEFORE {operation} ON workflow_taskstateevent
                WHEN {event_predicate}
                     AND NOT EXISTS (
                         SELECT 1
                         FROM contentops_tasksubmission submission
                         WHERE submission.id = NEW.submission_id
                           AND submission.task_id = NEW.task_id
                     )
                BEGIN
                    SELECT RAISE(ABORT, 'submission exit belongs to another task');
                END;
                """
            )
        return
    if vendor == "postgresql":
        schema_editor.execute(
            f"""
            CREATE FUNCTION workflow_enforce_withdrawal_task_match() RETURNS trigger AS $$
            BEGIN
                IF {event_predicate} AND NOT EXISTS (
                    SELECT 1
                    FROM contentops_tasksubmission submission
                    WHERE submission.id = NEW.submission_id
                      AND submission.task_id = NEW.task_id
                ) THEN
                    RAISE EXCEPTION 'submission exit belongs to another task'
                        USING ERRCODE = '23514';
                END IF;
                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;
            """
        )
        schema_editor.execute(
            """
            CREATE TRIGGER workflow_withdrawal_task_match_guard
            BEFORE INSERT OR UPDATE ON workflow_taskstateevent
            FOR EACH ROW EXECUTE FUNCTION workflow_enforce_withdrawal_task_match();
            """
        )


def upgrade_submission_exit_integrity(apps, schema_editor):
    _drop_submission_exit_integrity_trigger(schema_editor)
    _create_submission_exit_integrity_trigger(
        schema_editor,
        include_abandonment=True,
    )


def downgrade_submission_exit_integrity(apps, schema_editor):
    _drop_submission_exit_integrity_trigger(schema_editor)
    _create_submission_exit_integrity_trigger(
        schema_editor,
        include_abandonment=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_secretreference_permissiongrant_supersedes_grant_and_more'),
        ('contentops', '0005_owner_self_approval_policy'),
        ('workflow', '0005_approved_rework_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='taskstateevent',
            name='workflow_event_type_payload_shape',
        ),
        migrations.RemoveConstraint(
            model_name='taskstateevent',
            name='workflow_one_withdrawal_per_submission',
        ),
        migrations.AlterField(
            model_name='taskstateevent',
            name='event_type',
            field=models.CharField(choices=[('STATE_TRANSITION', 'State transition'), ('SUBMISSION_WITHDRAWN', 'Submission withdrawn'), ('SUBMISSION_ABANDONED', 'Submission abandoned with task cancellation'), ('APPROVED_REWORK_REQUESTED', 'Approved submission returned for rework')], default='STATE_TRANSITION', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='taskstateevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_type', 'STATE_TRANSITION'), ('submission__isnull', True)), models.Q(('event_type', 'SUBMISSION_WITHDRAWN'), ('from_state', 'UNDER_REVIEW'), ('submission__isnull', False), ('to_state', 'IN_PROGRESS')), models.Q(('event_type', 'SUBMISSION_ABANDONED'), ('from_state', 'UNDER_REVIEW'), ('submission__isnull', False), ('to_state', 'CANCELLED')), models.Q(('event_type', 'APPROVED_REWORK_REQUESTED'), ('from_state', 'APPROVED'), ('submission__isnull', False), ('to_state', 'HUMAN_REWORK')), _connector='OR'), name='workflow_event_type_payload_shape'),
        ),
        migrations.AddConstraint(
            model_name='taskstateevent',
            constraint=models.UniqueConstraint(condition=models.Q(('event_type__in', ('SUBMISSION_WITHDRAWN', 'SUBMISSION_ABANDONED'))), fields=('submission',), name='workflow_one_review_exit_per_submission'),
        ),
        migrations.RunPython(
            upgrade_submission_exit_integrity,
            downgrade_submission_exit_integrity,
        ),
    ]
