# Generated by Django 5.2.15 on 2026-08-18 15:52

import core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('market_code', models.CharField(max_length=16)),
                ('language_code', models.CharField(max_length=16)),
                ('product_status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=16)),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductProfileVersion',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('market_code', models.CharField(max_length=16)),
                ('language_code', models.CharField(max_length=16)),
                ('audience', models.JSONField(default=dict)),
                ('core_value_proposition', models.TextField()),
                ('brand_voice', models.JSONField(default=dict)),
                ('product_facts', models.JSONField(default=dict)),
                ('prohibited_expressions', models.JSONField(default=list)),
                ('objective_profile_key', models.CharField(default='VISIBILITY_AND_SEO_PROOF', max_length=100)),
                ('manifest_sha256', models.CharField(blank=True, max_length=64)),
                ('sealed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_profiles_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profile_versions', to='products.product')),
                ('sealed_by_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_profiles_sealed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='current_profile_version',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_product', to='products.productprofileversion'),
        ),
        migrations.AddConstraint(
            model_name='productprofileversion',
            constraint=models.UniqueConstraint(fields=('product', 'version_number'), name='products_unique_profile_version'),
        ),
        migrations.AddConstraint(
            model_name='productprofileversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('sealed_at__isnull', True), ('sealed_by_principal__isnull', True)), models.Q(('sealed_at__isnull', False), ('sealed_by_principal__isnull', False), models.Q(('manifest_sha256', ''), _negated=True)), _connector='OR'), name='products_profile_complete_seal'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('product_code', 'market_code', 'language_code'), name='products_unique_code_market_language'),
        ),
    ]
