# Generated by Django 5.2.15 on 2026-08-21 09:05

import core.ids
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentops', '0003_tasksubmission_contentops_submission_cannot_supersede_self'),
        ('insights', '0001_initial'),
        ('products', '0001_initial'),
        ('releasegate', '0004_alter_publication_requested_by_acting_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimMatrixVersion',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('manifest_sha256', models.CharField(blank=True, max_length=64)),
                ('sealed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_number', models.PositiveIntegerField()),
                ('market_code', models.CharField(max_length=16)),
                ('language_code', models.CharField(max_length=16)),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_matrices', to='products.product')),
                ('sealed_by_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='productprofileversion',
            name='claim_matrix_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_profiles', to='products.claimmatrixversion'),
        ),
        migrations.CreateModel(
            name='ControlledEvidenceItemVersion',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('evidence_key', models.CharField(max_length=120)),
                ('version_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=240)),
                ('provider', models.CharField(max_length=120)),
                ('external_url', models.URLField(max_length=2048)),
                ('version_reference', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('content_sha256', models.CharField(blank=True, max_length=64)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controlled_evidence', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceLibraryVersion',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('manifest_sha256', models.CharField(blank=True, max_length=64)),
                ('sealed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_number', models.PositiveIntegerField()),
                ('market_code', models.CharField(max_length=16)),
                ('language_code', models.CharField(max_length=16)),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_libraries', to='products.product')),
                ('sealed_by_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceLibraryItem',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('controlled_evidence_item_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='library_items', to='products.controlledevidenceitemversion')),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('evidence_library_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='products.evidencelibraryversion')),
            ],
        ),
        migrations.AddField(
            model_name='productprofileversion',
            name='evidence_library_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_profiles', to='products.evidencelibraryversion'),
        ),
        migrations.CreateModel(
            name='ObjectiveProfileVersion',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('manifest_sha256', models.CharField(blank=True, max_length=64)),
                ('sealed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('objective_key', models.CharField(max_length=100)),
                ('version_number', models.PositiveIntegerField()),
                ('primary_objectives', models.JSONField(default=list)),
                ('secondary_objectives', models.JSONField(default=list)),
                ('retained_metrics', models.JSONField(default=list)),
                ('priority_rules', models.JSONField(default=dict)),
                ('strategy_boundaries', models.JSONField(default=dict)),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sealed_by_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectiveMetricLink',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('metric_role', models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('GUARDRAIL', 'Guardrail'), ('RETAIN_ONLY', 'Retain only')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('metric_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objective_links', to='insights.metricdefinition')),
                ('objective_profile_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metric_links', to='products.objectiveprofileversion')),
            ],
        ),
        migrations.AddField(
            model_name='productprofileversion',
            name='objective_profile_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_profiles', to='products.objectiveprofileversion'),
        ),
        migrations.CreateModel(
            name='ProductClaimVersion',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('claim_key', models.CharField(max_length=120)),
                ('version_number', models.PositiveIntegerField()),
                ('claim_type', models.CharField(choices=[('ALLOWED', 'Allowed'), ('RESTRICTED', 'Restricted'), ('PROHIBITED', 'Prohibited')], max_length=16)),
                ('market_code', models.CharField(max_length=16)),
                ('platform_code', models.CharField(blank=True, max_length=64)),
                ('evidence_level', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('UNSUPPORTED', 'Unsupported')], max_length=16)),
                ('wording', models.TextField()),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_versions', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimMatrixItem',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('claim_matrix_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='products.claimmatrixversion')),
                ('product_claim_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matrix_items', to='products.productclaimversion')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimEvidenceLink',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('evidence_reference', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('controlled_evidence_item_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_links', to='products.controlledevidenceitemversion')),
                ('product_claim_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_links', to='products.productclaimversion')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProfileAssetLink',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('asset_kind', models.CharField(choices=[('LOGO', 'Logo'), ('VISUAL_SPEC', 'Visual specification'), ('PRODUCT_IMAGE_LINK', 'Product image link'), ('LITERATURE_LINK', 'Literature link'), ('CONTROLLED_EVIDENCE', 'Controlled evidence')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_asset_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_profile_links', to='contentops.contentassetversion')),
                ('controlled_evidence_item_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_profile_links', to='products.controlledevidenceitemversion')),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product_profile_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_links', to='products.productprofileversion')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProfilePolicyLink',
            fields=[
                ('id', models.UUIDField(default=core.ids.uuid7, editable=False, primary_key=True, serialize=False)),
                ('policy_role', models.CharField(choices=[('APPLICABLE', 'Applicable'), ('OVERRIDE', 'Override'), ('EXPERIMENTAL', 'Experimental')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('policy_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_profile_links', to='releasegate.policyversion')),
                ('product_profile_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policy_links', to='products.productprofileversion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='claimmatrixversion',
            constraint=models.UniqueConstraint(fields=('product', 'version_number'), name='products_unique_claim_matrix_version'),
        ),
        migrations.AddConstraint(
            model_name='controlledevidenceitemversion',
            constraint=models.UniqueConstraint(fields=('product', 'evidence_key', 'version_number'), name='products_unique_controlled_evidence_version'),
        ),
        migrations.AddConstraint(
            model_name='controlledevidenceitemversion',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='products_evidence_valid_window'),
        ),
        migrations.AddConstraint(
            model_name='evidencelibraryversion',
            constraint=models.UniqueConstraint(fields=('product', 'version_number'), name='products_unique_evidence_library_version'),
        ),
        migrations.AddConstraint(
            model_name='evidencelibraryitem',
            constraint=models.UniqueConstraint(fields=('evidence_library_version', 'controlled_evidence_item_version'), name='products_unique_evidence_library_item'),
        ),
        migrations.AddConstraint(
            model_name='objectiveprofileversion',
            constraint=models.UniqueConstraint(fields=('objective_key', 'version_number'), name='products_unique_objective_profile_version'),
        ),
        migrations.AddConstraint(
            model_name='objectiveprofileversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_number__gte', 1)), name='products_objective_version_gte_one'),
        ),
        migrations.AddConstraint(
            model_name='objectivemetriclink',
            constraint=models.UniqueConstraint(fields=('objective_profile_version', 'metric_definition', 'metric_role'), name='products_unique_objective_metric_role'),
        ),
        migrations.AddConstraint(
            model_name='productclaimversion',
            constraint=models.UniqueConstraint(fields=('product', 'claim_key', 'version_number'), name='products_unique_claim_version'),
        ),
        migrations.AddConstraint(
            model_name='productclaimversion',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='products_claim_valid_window'),
        ),
        migrations.AddConstraint(
            model_name='claimmatrixitem',
            constraint=models.UniqueConstraint(fields=('claim_matrix_version', 'product_claim_version'), name='products_unique_claim_matrix_item'),
        ),
        migrations.AddConstraint(
            model_name='claimevidencelink',
            constraint=models.UniqueConstraint(fields=('product_claim_version', 'controlled_evidence_item_version'), name='products_unique_claim_evidence_link'),
        ),
        migrations.AddConstraint(
            model_name='productprofileassetlink',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('content_asset_version__isnull', False), ('controlled_evidence_item_version__isnull', True)), models.Q(('content_asset_version__isnull', True), ('controlled_evidence_item_version__isnull', False)), _connector='OR'), name='products_profile_asset_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='productprofilepolicylink',
            constraint=models.UniqueConstraint(fields=('product_profile_version', 'policy_version', 'policy_role'), name='products_unique_profile_policy_link'),
        ),
    ]
